#pragma once

#include <common.h>
#include <cpu.h>

void LD_B_N(CPU &cpu, u8 n);
void LD_C_N(CPU &cpu, u8 n);
void LD_D_N(CPU &cpu, u8 n);
void LD_E_N(CPU &cpu, u8 n);
void LD_H_N(CPU &cpu, u8 n);
void LD_L_N(CPU &cpu, u8 n);
void LD_A_A(CPU &cpu);
void LD_A_B(CPU &cpu);
void LD_A_C(CPU &cpu);
void LD_A_D(CPU &cpu);
void LD_A_E(CPU &cpu);
void LD_A_H(CPU &cpu);
void LD_A_HL(CPU &cpu);
void LD_B_B(CPU &cpu);
void LD_B_C(CPU &cpu);
void LD_B_D(CPU &cpu);
void LD_B_E(CPU &cpu);
void LD_B_H(CPU &cpu);
void LD_B_L(CPU &cpu);
void LD_B_HL(CPU &cpu);
void LD_C_B(CPU &cpu);
void LD_C_C(CPU &cpu);
void LD_C_D(CPU &cpu);
void LD_C_E(CPU &cpu);
void LD_C_H(CPU &cpu);
void LD_C_L(CPU &cpu);
void LD_C_HL(CPU &cpu);
void LD_D_B(CPU &cpu);
void LD_D_C(CPU &cpu);
void LD_D_D(CPU &cpu);
void LD_D_E(CPU &cpu);
void LD_D_F(CPU &cpu);
void LD_D_H(CPU &cpu);
void LD_D_L(CPU &cpu);
void LD_D_HL(CPU &cpu);
void LD_E_B(CPU &cpu);
void LD_E_C(CPU &cpu);
void LD_E_D(CPU &cpu);
void LD_E_E(CPU &cpu);
void LD_E_F(CPU &cpu);
void LD_E_H(CPU &cpu);
void LD_E_L(CPU &cpu);
void LD_E_HL(CPU &cpu);
void LD_H_B(CPU &cpu);
void LD_H_C(CPU &cpu);
void LD_H_D(CPU &cpu);
void LD_H_E(CPU &cpu);
void LD_H_F(CPU &cpu);
void LD_H_H(CPU &cpu);
void LD_H_L(CPU &cpu);
void LD_H_HL(CPU &cpu);
void LD_L_B(CPU &cpu);
void LD_L_C(CPU &cpu);
void LD_L_D(CPU &cpu);
void LD_L_E(CPU &cpu);
void LD_L_F(CPU &cpu);
void LD_L_H(CPU &cpu);
void LD_L_L(CPU &cpu);
void LD_L_HL(CPU &cpu);
void LD_HL_B(CPU &cpu);
void LD_HL_C(CPU &cpu);
void LD_HL_D(CPU &cpu);
void LD_HL_E(CPU &cpu);
void LD_HL_F(CPU &cpu);
void LD_HL_H(CPU &cpu);
void LD_HL_L(CPU &cpu);
void LD_HL_HL(CPU &cpu);
void LD_HL_N(CPU &cpu);
void LD_A_BC(CPU &cpu);
void LD_A_DE(CPU &cpu);
void LD_A_NN(CPU &cpu, u16 nn);
void LD_B_A(CPU &cpu);
void LD_C_A(CPU &cpu);
void LD_D_A(CPU &cpu);
void LD_E_A(CPU &cpu);
void LD_F_A(CPU &cpu);
void LD_H_A(CPU &cpu);
void LD_L_A(CPU &cpu);
void LD_BC_A(CPU &cpu);
void LD_DE_A(CPU &cpu);
void LD_HL_A(CPU &cpu);
void LD_NN_A(CPU &cpu, u16 nn);
void LD_A_PAREN_C(CPU &cpu, MMU &mmu);
void LD_PAREN_C_A(CPU &cpu, MMU &mmu);
void LDD_A_PAREN_HL(CPU &cpu, MMU &mmu);
void LDD_PAREN_HL_A(CPU &cpu, MMU &mmu);
void LDI_A_PAREN_HL(CPU &cpu, MMU &mmu);
void LDI_PAREN_HL_A(CPU &cpu, MMU &mmu);
void LDH_PAREN_N_A(CPU &cpu, MMU &mmu, u8 n);
void LDH_A_PAREN_N(CPU &cpu, MMU &mmu, u8 n);
void LD_BC_NN(CPU &cpu, u16 nn);
void LD_DE_NN(CPU &cpu, u16 nn);
void LD_HL_NN(CPU &cpu, u16 nn);
void LD_SP_NN(CPU &cpu, u16 nn);
void LD_SP_HL(CPU &cpu);
